name: Terraform Destroy

on:
  workflow_dispatch: # omogućava ručno pokretanje iz Actions taba

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    env:
      SSH_KEY_NAME: ${{ secrets.SSH_KEY_NAME }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Init
        run: terraform init

      - name: Create terraform.tfvars from secrets
        run: |
          echo "ssh_key_name = \"${{ env.SSH_KEY_NAME }}\"" >> terraform.tfvars
          echo "db_name = \"${{ env.DB_NAME }}\"" >> terraform.tfvars
          echo "db_password = \"${{ env.DB_PASSWORD }}\"" >> terraform.tfvars

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"
